// <auto-generated />
using ConsoleApp3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ConsoleApp3.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT (200)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ConsoleApp3.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT (250)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUser")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idUser");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT (250)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT (250)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ConsoleApp3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT (200)")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roleID");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT (200)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsoleApp3.Models.Task", b =>
                {
                    b.HasOne("ConsoleApp3.Models.User", "IdUserNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("IdUser");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ConsoleApp3.Models.User", b =>
                {
                    b.HasOne("ConsoleApp3.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConsoleApp3.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ConsoleApp3.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
